travis:
  secure:
    BINSTAR_TOKEN: l4kVDvHiQqxc9mP/V8AiZV/yTvau1Ir+6Ygw9lJ4TRYeBHU2QsBh9gUga3ZsK+MbmKvPde5aYMkoeJOWEciDE9bEy51sgzOfWP3Fa2QumCx9uC/vn6Ojdp876nG3P6n4IZmwJmFaJsyAo1y4/DYHjmPoHDWTcF4nVRZI34XhZcHgzz7UoUMX7G3BE2CI/oeOM1lNRhqoo1KHWa5zE/5pew68/5b3x51nmbqxKKxoRwHTwVzRQPO18QQdv2Lb9GH3pt83E9sWXOyESEwqMe1PNiYBlTxp0GN/989FG76xTDgwiySkXz8aOiajp5tEOkL0nsRci5T+pXrMysgeqYECyc9fuLJF2OTZ++dXV6EFXawtLMgEXT19rtD7khHs5AuvlQnj0WN+ohOSfDXmeW7vyO5oinGUyqN3sHZZZggpeGSwnIbrH4wT9zoRXKUwMjHbK1ebs72lDbODJZGx6HfvDW7P7LBidzzKaTs6MH8tWwNHwnJ0dtrzZRWEYjPOvBoPIvStirrr9UANeIbgnu0OskJ7AAacTHaSuOxlsL74SbojjWKxhNhfKa31SAL03ukoqofujzgLz2e+RLyc0zT8ioYbTiI/oFvBUPp6ca5O48Kde+NZoB4TSV75t+GJeDSgJQbB67A6Qpa4x3pCA1pmO75a/ZWLU5gyPKhRcyZUXz8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
